---
- name: Run systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart byedpi
  ansible.builtin.systemd_service:
    name: byedpi
    state: restarted
  become: true
