---
# @var sthp_bin:description: путь к исполняемому файлу sthp
sthp_bin: "{{ ansible_user_dir }}/.local/bin/sthp"

# @var sthp_port:description: порт на котором слушает http прокси
sthp_port: 1085

# @var sthp_socks_porxy:description: адрес socks5 прокси
sthp_socks_porxy: '127.0.0.1:5832'
