---
- name: Install kitty
  ansible.builtin.package:
    state: present
    name: kitty
    update_cache: true
  become: true
  tags: kitty

- name: Create kitty config directory
  ansible.builtin.file:
    state: directory
    path: "{{ kitty_home }}"
    mode: "0755"
  tags: kitty

- name: Deploy kitty configuration
  ansible.builtin.template:
    src: kitty.conf.j2
    dest: "{{ kitty_home }}/kitty.conf"
    mode: "0644"
  tags: kitty

- name: Deploy kitty theme configuration
  ansible.builtin.template:
    src: current-theme.conf.j2
    mode: "0644"
  tags: kitty
