---
- name: Create systemd user directory
  ansible.builtin.file:
    state: directory
    path: "{{ ansible_user_dir }}/.config/systemd/user"
    mode: "0755"
  tags:
    - sthp

- name: Deploy sthp user service
  ansible.builtin.template:
    src: sthp.service.j2
    dest: "{{ ansible_user_dir }}/.config/systemd/user/sthp.service"
    mode: "0644"
  notify:
    - Reload systemd
    - Restart sthp
  tags:
    - sthp

- name: Enable and start sthp
  ansible.builtin.systemd:
    scope: user
    name: sthp
    enabled: true
    state: started
    daemon_reload: true
  tags:
    - sthp
