---
galaxy_info:
  author: Stanislav Korolev
  namespace: things
  description: Install login manager [slim](https://wiki.archlinux.org/title/SLiM)
  company: RootIT
  license: ISC
  min_ansible_version: '2.12'
  platforms:
    - name: Debian
      versions:
        - all
