---
# @var torrserver_version:description: версия torrserver
torrserver_version: 137

# @var torrserver_deb_version:description: версия deb пакета
torrserver_deb_version: '{{ torrserver_version }}-2'
