---
galaxy_info:
  author: Stanislav Korolev
  namespace: things
  description: Install [Chatwoot](https://www.chatwoot.com/) from the official deb
  company: RootIT
  license: ISC
  min_ansible_version: '2.12'
  platforms:
    - name: Debian
      versions:
        - all
